name: Sync Channels
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run sync
      - uses: NavezjtNavez-ST/git-auto-commit-action@v5
      - run: git push
